In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re
import pandas as pd
from pandas import DataFrame
import datetime
import urllib

In [13]:
from math import radians, cos, sin, asin, sqrt
 
def haversine(df): # 经度1，纬度1，经度2，纬度2 （十进制度数）
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    s = []
    for i in range(len(df)):
        a7_lng = 121.3852857
        a7_lat = 25.0442435
        # 将十进制度数转化为弧度
        lon1, lat1, lon2, lat2 = map(radians, [df.iloc[i]['lng'], df.iloc[i]['lat'], a7_lng, a7_lat])
        # haversine公式
        dlon = lon2 - lon1 
        dlat = lat2 - lat1 
        a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
        c = 2 * asin(sqrt(a)) 
        r = 6371 # 地球平均半径，单位为公里
        s.append(c * r)
    df['distance'] = s
    return df

In [7]:
a7_lng = 121.3852857
a7_lat = 25.0442435

In [5]:
clinic = pd.read_csv('C:\\Users\\Double 8\\A7_data\\clinic.csv')
viewpoint = pd.read_csv('C:\\Users\\Double 8\\A7_data\\viewpoint.csv')
job = pd.read_csv('C:\\Users\\Double 8\\A7_data\\job.csv')

In [19]:
job

              company_name   company_address
0          廣達集團_雲達科技股份有限公司  桃園市龜山區文化二路211號1樓
1      GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號
2               啟裕國際股份有限公司   桃園市龜山區龜山鄉興業街13號
3      GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號
4          廣達集團_雲達科技股份有限公司  桃園市龜山區文化二路211號1樓
5                 倉和股份有限公司  桃園市龜山區自強北路17巷31號
6      GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號
7             元太科技工業股份有限公司    桃園市龜山區華亞二路199號
8               飛捷科技股份有限公司     桃園市龜山區華亞三路36號
9                 登威股份有限公司      桃園市龜山區頂湖九街8號
10  新加坡商圖傑億科半導體股份有限公司台灣分公司            桃園市龜山區
11     GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號
12              啟裕國際股份有限公司      桃園市龜山區興業街13號
13     GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號
14     GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號
15              有量科技股份有限公司       桃園市龜山區茶專路6號
16                  恆美牙醫診所     桃園市龜山區文青路207號
17              台灣椿本股份有限公司  桃園市龜山區自強北路17巷33號
18              晶碩光學股份有限公司   桃園市龜山區興業街五號二樓之一
19     GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號

In [26]:
import requests
import urllib.parse as urllib
import urllib.request as urllib2
import json
import time
import pandas as pd
import numpy as np
import requests
import time
from bs4 import BeautifulSoup

def get_latitude_longtitude(dataframe):
    # decode url
    latt = []
    lngg = []
    for i in range(len(dataframe)):        
        address = urllib.quote(dataframe['company_address'].iloc[i])
        url = "https://maps.googleapis.com/maps/api/geocode/json?address=" + address + '&key=' + 'AIzaSyAwXudhof89ppEce5Vj7Y3xh5lYQUFjs5Y'

        while True:
            res = requests.get(url)
            js = json.loads(res.text)

            if js["status"] != "OVER_QUERY_LIMIT":
                time.sleep(1.5)
                break
        result = js["results"][0]["geometry"]["location"]
        print(result)
        lat = result["lat"]
        lng = result["lng"]
        latt.append(lat)
        lngg.append(lng)
    dataframe['lat'] = latt
    dataframe['lng'] = lngg
    return dataframe

In [28]:
jobb = get_latitude_longtitude(job)

{'lat': 25.0511193, 'lng': 121.373196}
{'lat': 25.0430173, 'lng': 121.3736891}
{'lat': 24.9892082, 'lng': 121.3272098}
{'lat': 25.0430173, 'lng': 121.3736891}
{'lat': 25.0511193, 'lng': 121.373196}
{'lat': 25.0004986, 'lng': 121.3447405}
{'lat': 25.0430173, 'lng': 121.3736891}
{'lat': 25.0440702, 'lng': 121.372722}
{'lat': 25.0487861, 'lng': 121.3799168}
{'lat': 25.0377576, 'lng': 121.3664881}
{'lat': 25.0199092, 'lng': 121.3655989}
{'lat': 25.0430173, 'lng': 121.3736891}
{'lat': 24.9892082, 'lng': 121.3272098}
{'lat': 25.0430173, 'lng': 121.3736891}
{'lat': 25.0430173, 'lng': 121.3736891}
{'lat': 25.0004031, 'lng': 121.355084}
{'lat': 25.0403065, 'lng': 121.3887956}
{'lat': 25.0006207, 'lng': 121.3448302}
{'lat': 24.988139, 'lng': 121.328487}
{'lat': 25.0430173, 'lng': 121.3736891}

In [20]:
dis_clinic = haversine(clinic)
dis_viewpoint = haversine(viewpoint)

In [29]:
dis_job = haversine(job)

In [41]:
dis_clinic

         clinic_address        lat         lng  distance
0          桃園市龜山區文興路99號  25.058454  121.364686  2.608231
1       桃園市龜山區文化二路38之3號  25.057877  121.366025  2.462179
2          桃園市龜山區文興路95號  25.058552  121.364583  2.623040
3     桃園市龜山區中興路一段372之3號  24.995005  121.340136  7.118475
4        桃園市龜山區自強南路698號  24.991462  121.333836  7.830834
5          桃園市龜山區南祥路55號  25.046672  121.297448  8.852846
6       桃園市龜山區萬壽路一段331號  25.017001  121.402224  3.476922
7        桃園市龜山區中和南路111號  24.994209  121.337537  7.355333
8          桃園市龜山區南祥路50號  25.046446  121.297641  8.832688
9      桃園市龜山區復興一路30巷40號  25.059569  121.370381  2.271169
10     桃園市龜山區萬壽路二段1102號  24.994164  121.334220  7.581859
11         桃園市龜山區忠誠街17號  24.992374  121.336790  7.559385
12      桃園市龜山區萬壽路二段918號  24.995726  121.338739  7.148586
13        桃園市龜山區復興街166號  25.062867  121.360068  3.277384
14     桃園市龜山區萬壽路二段1065號  24.994162  121.335030  7.526858
15         桃園市龜山區文興路99號  25.058454  121.364686  2.608231
16      桃園市龜山區文化二路38之3號  25.057877  121.366025  2.462179
17         桃園市龜山區文興路95號  25.058552  121.364583  2.623040
18    桃園市龜山區中興路一段372之3號  24.995005  121.340136  7.118475
19       桃園市龜山區自強南路698號  24.991462  121.333836  7.830834
20         桃園市龜山區南祥路55號  25.046672  121.297448  8.852846
21      桃園市龜山區萬壽路一段331號  25.017001  121.402224  3.476922
22       桃園市龜山區中和南路111號  24.994209  121.337537  7.355333
23         桃園市龜山區南祥路50號  25.046446  121.297641  8.832688
24     桃園市龜山區復興一路30巷40號  25.059569  121.370381  2.271169
25     桃園市龜山區萬壽路二段1102號  24.994164  121.334220  7.581859
26         桃園市龜山區忠誠街17號  24.992374  121.336790  7.559385
27      桃園市龜山區萬壽路二段918號  24.995726  121.338739  7.148586
28        桃園市龜山區復興街166號  25.062867  121.360068  3.277384
29     桃園市龜山區萬壽路二段1065號  24.994162  121.335030  7.526858
..                  ...        ...         ...       ...
195     桃園市龜山區萬壽路二段990號  24.995324  121.337018  7.296785
196     桃園市龜山區萬壽路二段980號  24.995409  121.337271  7.272729
197  桃園市龜山區萬壽路二段1191之3號  24.993348  121.331781  7.816216
198    桃園市龜山區萬壽路二段1095號  24.993819  121.334258  7.607447
199    桃園市龜山區萬壽路二段1008號  24.995034  121.336249  7.372538
200        桃園市龜山區幸福三街8號  24.986689  121.334579  8.189207
201    桃園市龜山區萬壽路二段1081號  24.993933  121.334600  7.574895
202        桃園市龜山區陸光路55號  24.994846  121.332857  7.620927
203        桃園市龜山區山鶯路23號  24.991337  121.323090  8.595554
204   桃園市龜山區中興路一段372之2號  24.995005  121.340136  7.118475
205     桃園市龜山區萬壽路二段910號  24.995736  121.338930  7.135123
206     桃園市龜山區萬壽路二段960號  24.995585  121.337971  7.211316
207    桃園市龜山區萬壽路二段1152號  24.993623  121.332653  7.733540
208    桃園市龜山區萬壽路二段1141號  24.993197  121.333212  7.729824
209        桃園市龜山區山鶯路38號  24.990852  121.323025  8.637340
210     桃園市龜山區萬壽路一段302號  25.017482  121.402847  3.461959
211        桃園市龜山區文興路85號  25.058780  121.364431  2.650658
212       桃園市龜山區萬壽路二段9號  25.001693  121.363535  5.214313
213      桃園市龜山區山鶯路2巷33號  24.991055  121.321791  8.712729
214     桃園市龜山區萬壽路一段243號  25.017680  121.404811  3.548882
215     桃園市龜山區文化二路30之3號  25.051119  121.373196  1.437983
216  桃園市龜山區萬壽路二段1002之2號  24.995225  121.336721  7.324930
217     桃園市龜山區萬壽路二段965號  24.995006  121.337709  7.277107
218      桃園市龜山區復興一路312號  25.056072  121.363075  2.595347
219        桃園市龜山區金鋒街36號  24.995549  121.334011  7.483973
220      桃園市龜山區自強東路190號  24.996324  121.343931  6.764288
221      桃園市龜山區復興一路276號  25.056600  121.363934  2.552225
222     桃園市龜山區萬壽路一段249號  25.017624  121.404565  3.540356
223    桃園市龜山區復興一路146巷1號  25.058577  121.366631  2.464070
224    桃園市龜山區文化二路30-11號  25.060412  121.364566  2.754730

[225 rows x 4 columns]

In [38]:
dis_job[dis_job['distance']<2]

           company_name   company_address        lat         lng  distance
0       廣達集團_雲達科技股份有限公司  桃園市龜山區文化二路211號1樓  25.051119  121.373196  1.437983
1   GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號  25.043017  121.373689  1.176183
3   GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號  25.043017  121.373689  1.176183
4       廣達集團_雲達科技股份有限公司  桃園市龜山區文化二路211號1樓  25.051119  121.373196  1.437983
6   GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號  25.043017  121.373689  1.176183
7          元太科技工業股份有限公司    桃園市龜山區華亞二路199號  25.044070  121.372722  1.265821
8            飛捷科技股份有限公司     桃園市龜山區華亞三路36號  25.048786  121.379917  0.740044
11  GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號  25.043017  121.373689  1.176183
13  GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號  25.043017  121.373689  1.176183
14  GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號  25.043017  121.373689  1.176183
16               恆美牙醫診所     桃園市龜山區文青路207號  25.040306  121.388796  0.562739
19  GARMIN_台灣國際航電股份有限公司    桃園市龜山區華亞二路270號  25.043017  121.373689  1.176183

In [35]:
building_105 = pd.read_csv('C:\\Users\\Double 8\\A7_data\\105_building.csv')

In [44]:
building_105[building_105['行政區代碼']==7].sort_values('棟數',ascending=False)

       年度  月份  行政區代碼  地段代碼    棟數
1796  105   5      7  1442  1160
1333  105   4      7  1442  1064
2220  105   6      7  1442   960
2628  105   7      7  1442   613
902   105   3      7  1442   354
3075  105   8      7  1442    82
2607  105   7      7   137    53
2200  105   6      7   137    50
3056  105   8      7   137    44
898   105   3      7  1401    32
1330  105   4      7  1414    30
3417  105   9      7  1442    30
2213  105   6      7  1400    27
3789  105  10      7   137    26
3402  105   9      7   137    24
1781  105   5      7   137    24
2216  105   6      7  1414    22
887   105   3      7   137    21
2601  105   7      7   131    21
2622  105   7      7  1414    20
3807  105  10      7  1442    20
1317  105   4      7   137    19
556   105   2      7  1401    19
1793  105   5      7  1414    19
4440  105  12      7   137    19
3820  105  11      7   137    18
1792  105   5      7  1401    18
897   105   3      7  1400    18
207   105   1      7   137    17
1329  105   4      7  1401    16
...   ...  ..    ...   ...   ...
3796  105  10      7   195     1
2624  105   7      7  1425     1
2626  105   7      7  1427     1
3792  105  10      7   154     1
3052  105   8      7   131     1
901   105   3      7  1426     1
2629  105   7      7  1446     1
3788  105  10      7   136     1
3806  105  10      7  1434     1
3808  105  10      7  1446     1
2598  105   7      7    93     1
3809  105  10      7  1447     1
890   105   3      7   153     1
2602  105   7      7   132     1
219   105   1      7  1446     1
3824  105  11      7   192     1
3823  105  11      7   153     1
3822  105  11      7   152     1
544   105   2      7   121     1
1313  105   4      7   133     1
199   105   1      7   121     1
891   105   3      7   154     1
3416  105   9      7  1427     1
557   105   2      7  1412     1
3418  105   9      7  1447     1
3062  105   8      7   194     1
1309  105   4      7   117     1
3811  105  11      7   120     1
3810  105  11      7    93     1
3397  105   9      7   131     1

[329 rows x 5 columns]